#!/bin/csh

/bin/rm outfile
touch outfile

foreach i (00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25)
  make test$i
  echo starting test $i ....  >> outfile
  echo >> outfile
  ./test$i >>& outfile
  echo >> outfile
  rm test$i.o test$i
end
